import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import {
  api, type CoverageItem, type Dashboard, type DirectoryUser, type Member, type Milestone, type QualityReport,
  type Schedule, type TestCase, type TestPlan, type TestSuite, type User, type Version, type WorkItem,
} from './api';
import { Empty, formatDate, labels, Modal, PageHeader, ProgressBar, StatusBadge } from './ui';

const total = (rows: { count: number }[], predicate: (row: { count: number } & Record<string, unknown>) => boolean = () => true) =>
  rows.filter((row) => predicate(row as { count: number } & Record<string, unknown>)).reduce((sum, row) => sum + Number(row.count), 0);

function formObject(form: HTMLFormElement): Record<string, FormDataEntryValue> {
  return Object.fromEntries(new FormData(form).entries());
}

export function Overview({ projectId }: { projectId: string }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [report, setReport] = useState<QualityReport | null>(null);
  const [milestones, setMilestones] = useState<Milestone[]>([]);
  const [plans, setPlans] = useState<TestPlan[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const load = useCallback(async () => {
    const [dashboardResult, reportResult, milestoneResult, planResult] = await Promise.all([
      api<Dashboard>(`/api/projects/${projectId}/dashboard`), api<QualityReport>(`/api/projects/${projectId}/reports`),
      api<{ items: Milestone[] }>(`/api/projects/${projectId}/milestones`), api<{ items: TestPlan[] }>(`/api/projects/${projectId}/test-plans`),
    ]);
    setDashboard(dashboardResult); setReport(reportResult); setMilestones(milestoneResult.items); setPlans(planResult.items);
  }, [projectId]);
  useEffect(() => { void load(); }, [load]);
  const seed = async () => {
    setBusy(true); setError('');
    try { await api(`/api/projects/${projectId}/demo-seed`, { method: 'POST' }); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : '填充失败'); }
    finally { setBusy(false); }
  };
  if (!dashboard || !report) return <div className="loading-state">正在汇总项目数据…</div>;
  const requirements = total(dashboard.work_items, (row) => row.kind === 'requirement');
  const bugs = total(dashboard.work_items, (row) => row.kind === 'bug');
  const openBugs = total(dashboard.work_items, (row) => row.kind === 'bug' && !['resolved', 'closed'].includes(String(row.status)));
  const cases = total(dashboard.test_cases);
  const executed = total(report.execution, (row) => row.result !== 'not_run');
  const passed = total(report.execution, (row) => row.result === 'passed');
  const passRate = executed ? Math.round((passed / executed) * 100) : 0;
  const coverageRate = report.coverage.total ? Math.round((report.coverage.covered / report.coverage.total) * 100) : 0;
  const isEmpty = requirements + bugs + cases === 0;
  return <div className="page-stack">
    <PageHeader eyebrow="PROJECT HEALTH" title="项目总览" description="从范围、进度与质量三个维度查看项目状态。" actions={isEmpty ? <button className="primary" disabled={busy} onClick={() => void seed()}>{busy ? '生成中…' : '填充虚构演示数据'}</button> : undefined}/>
    {error && <p className="error">{error}</p>}
    <div className="metric-grid metric-grid-five">
      <article className="metric accent-blue"><span>需求总数</span><strong>{requirements}</strong><small>{report.overdue} 项已逾期</small></article>
      <article className="metric accent-rose"><span>未关闭问题</span><strong>{openBugs}</strong><small>共 {bugs} 个问题</small></article>
      <article className="metric accent-violet"><span>测试用例</span><strong>{cases}</strong><small>{plans.length} 个测试计划</small></article>
      <article className="metric accent-green"><span>需求覆盖率</span><strong>{coverageRate}%</strong><ProgressBar value={coverageRate}/></article>
      <article className="metric accent-amber"><span>执行通过率</span><strong>{passRate}%</strong><ProgressBar value={passRate}/></article>
    </div>
    <div className="dashboard-grid">
      <section className="panel"><div className="panel-title"><div><h3>里程碑进度</h3><p>关键交付节点和风险状态</p></div><span className="badge">{milestones.length} 个节点</span></div>
        <div className="milestone-list">{milestones.slice(0, 5).map((item) => <article key={item.id}><div><strong>{item.title}</strong><span>{formatDate(item.due_date)}</span></div><div className="row-gap"><StatusBadge value={item.status}/><b>{item.progress}%</b></div><ProgressBar value={item.progress}/></article>)}{!milestones.length && <Empty title="暂无里程碑" description="在里程碑页面规划关键交付节点。"/>}</div>
      </section>
      <section className="panel"><div className="panel-title"><div><h3>测试计划</h3><p>当前执行状态</p></div></div>
        <div className="compact-list">{plans.slice(0, 5).map((plan) => { const done = Number(plan.passed_count) + Number(plan.failed_count) + Number(plan.blocked_count); const rate = plan.case_count ? Math.round(done / plan.case_count * 100) : 0; return <article key={plan.id}><div><strong>{plan.name}</strong><StatusBadge value={plan.status}/></div><p>{plan.environment} · {done}/{plan.case_count} 已执行</p><ProgressBar value={rate}/></article>; })}{!plans.length && <Empty title="暂无测试计划"/>}</div>
      </section>
    </div>
    <section className="panel"><div className="panel-title"><div><h3>最近活动</h3><p>最近 12 条关键操作</p></div></div>
      {dashboard.recent.length ? <ul className="activity-list">{dashboard.recent.map((event) => <li key={event.id}><span className="activity-dot"/><div><strong>{event.actor_name}</strong> {event.action} <b>{event.entity_type}</b><small>{new Date(event.created_at).toLocaleString()}</small></div></li>)}</ul> : <Empty title="还没有活动记录"/>}
    </section>
  </div>;
}

export function WorkItems({ projectId, kind }: { projectId: string; kind: 'requirement' | 'bug' }) {
  const [items, setItems] = useState<WorkItem[]>([]); const [versions, setVersions] = useState<Version[]>([]); const [members, setMembers] = useState<Member[]>([]);
  const [modal, setModal] = useState<WorkItem | 'new' | null>(null); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => {
    const [itemResult, versionResult, memberResult] = await Promise.all([
      api<{ items: WorkItem[] }>(`/api/projects/${projectId}/items?kind=${kind}`), api<{ items: Version[] }>(`/api/projects/${projectId}/versions`), api<{ items: Member[] }>(`/api/projects/${projectId}/members`),
    ]); setItems(itemResult.items); setVersions(versionResult.items); setMembers(memberResult.items);
  }, [projectId, kind]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => items.filter((item) => (!status || item.status === status) && (!query || `${item.code} ${item.title} ${item.description}`.toLowerCase().includes(query.toLowerCase()))), [items, query, status]);
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError(''); const body = formObject(event.currentTarget);
    const payload = { ...body, kind, assignee_id: body.assignee_id || null, version_id: body.version_id || null, planned_start: body.planned_start || null, planned_end: body.planned_end || null, estimate_points: body.estimate_points ? Number(body.estimate_points) : null };
    try { if (modal === 'new') await api(`/api/projects/${projectId}/items`, { method: 'POST', body: JSON.stringify(payload) }); else if (modal) await api(`/api/projects/${projectId}/items/${modal.id}`, { method: 'PATCH', body: JSON.stringify(payload) }); setModal(null); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败'); }
  };
  const update = async (item: WorkItem, patch: object) => { await api(`/api/projects/${projectId}/items/${item.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); await load(); };
  const remove = async (item: WorkItem) => { if (!confirm(`确认删除 ${item.code}？`)) return; await api(`/api/projects/${projectId}/items/${item.id}`, { method: 'DELETE' }); await load(); };
  const heading = kind === 'bug' ? '问题管理' : '需求管理';
  return <div className="page-stack">
    <PageHeader eyebrow={kind === 'bug' ? 'ISSUE TRACKING' : 'SCOPE MANAGEMENT'} title={heading} description={kind === 'bug' ? '记录复现路径、运行环境、严重程度并跟踪闭环。' : '管理需求范围、验收标准、负责人和接入排期。'} actions={<button className="primary" onClick={() => setModal('new')}>+ 新建{kind === 'bug' ? '问题' : '需求'}</button>}/>
    <section className="panel"><div className="filter-bar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索编号、标题或描述"/><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option><option value="open">待处理</option><option value="planned">已计划</option><option value="in_progress">进行中</option><option value="blocked">已阻塞</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select><span>共 {filtered.length} 条</span></div>
      <div className="table-wrap"><table><thead><tr><th>编号 / 标题</th><th>{kind === 'bug' ? '严重程度' : '优先级'}</th><th>状态</th><th>负责人</th><th>版本</th><th>计划完成</th><th></th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><button className="title-link" onClick={() => setModal(item)}><span className="code">{item.code}</span><strong>{item.title}</strong><small>{item.description || '暂无描述'}</small></button></td><td><span className={`priority ${item.priority}`}>{kind === 'bug' ? labels[item.severity ?? ''] ?? '未定级' : labels[item.priority] ?? item.priority}</span></td><td><select value={item.status} onChange={(event) => void update(item, { status: event.target.value })}><option value="open">待处理</option><option value="planned">已计划</option><option value="in_progress">进行中</option><option value="blocked">已阻塞</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></td><td>{item.assignee_name ?? '未分配'}</td><td>{item.version_name ?? '未关联'}</td><td>{formatDate(item.planned_end)}</td><td><button className="danger-link" onClick={() => void remove(item)}>删除</button></td></tr>)}{!filtered.length && <tr><td colSpan={7}><Empty title="没有匹配的数据"/></td></tr>}</tbody></table></div>
    </section>
    {modal && <Modal wide title={modal === 'new' ? `新建${kind === 'bug' ? '问题' : '需求'}` : `${modal.code} · 编辑详情`} onClose={() => setModal(null)}><form className="stack" onSubmit={(event) => void save(event)}>
      <label>标题<input name="title" defaultValue={modal === 'new' ? '' : modal.title} required maxLength={300}/></label>
      <label>详细说明<textarea name="description" defaultValue={modal === 'new' ? '' : modal.description} rows={4}/></label>
      <div className="three-cols"><label>优先级<select name="priority" defaultValue={modal === 'new' ? 'medium' : modal.priority}><option value="urgent">紧急</option><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></label><label>状态<select name="status" defaultValue={modal === 'new' ? 'open' : modal.status}><option value="open">待处理</option><option value="planned">已计划</option><option value="in_progress">进行中</option><option value="blocked">已阻塞</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label>{kind === 'bug' ? <label>严重程度<select name="severity" defaultValue={modal === 'new' ? 'major' : modal.severity ?? 'major'}><option value="critical">致命</option><option value="major">严重</option><option value="minor">一般</option><option value="trivial">轻微</option></select></label> : <label>工作量点数<input name="estimate_points" type="number" min="0" max="1000" defaultValue={modal === 'new' ? 0 : modal.estimate_points ?? 0}/></label>}</div>
      <div className="two-cols"><label>负责人<select name="assignee_id" defaultValue={modal === 'new' ? '' : modal.assignee_id ?? ''}><option value="">未分配</option>{members.map((member) => <option value={member.id} key={member.id}>{member.display_name}</option>)}</select></label><label>目标版本<select name="version_id" defaultValue={modal === 'new' ? '' : modal.version_id ?? ''}><option value="">未关联</option>{versions.map((version) => <option value={version.id} key={version.id}>{version.name}</option>)}</select></label></div>
      <div className="two-cols"><label>计划开始<input name="planned_start" type="date" defaultValue={modal === 'new' ? '' : modal.planned_start?.slice(0, 10) ?? ''}/></label><label>计划完成<input name="planned_end" type="date" defaultValue={modal === 'new' ? '' : modal.planned_end?.slice(0, 10) ?? ''}/></label></div>
      {kind === 'requirement' ? <label>验收标准<textarea name="acceptance_criteria" defaultValue={modal === 'new' ? '' : modal.acceptance_criteria ?? ''} rows={4} placeholder="逐条描述可验证的完成条件"/></label> : <><label>运行环境<input name="environment" defaultValue={modal === 'new' ? 'Staging' : modal.environment ?? ''}/></label><label>复现步骤<textarea name="reproduction_steps" defaultValue={modal === 'new' ? '' : modal.reproduction_steps ?? ''} rows={4}/></label><div className="two-cols"><label>预期结果<textarea name="expected_result" defaultValue={modal === 'new' ? '' : modal.expected_result ?? ''} rows={3}/></label><label>实际结果<textarea name="actual_result" defaultValue={modal === 'new' ? '' : modal.actual_result ?? ''} rows={3}/></label></div></>}
      {error && <p className="error">{error}</p>}<div className="actions"><button type="button" onClick={() => setModal(null)}>取消</button><button className="primary">保存</button></div>
    </form></Modal>}
  </div>;
}

export function Versions({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<Version[]>([]); const [modal, setModal] = useState<Version | 'new' | null>(null);
  const load = useCallback(() => api<{ items: Version[] }>(`/api/projects/${projectId}/versions`).then((result) => setItems(result.items)), [projectId]);
  useEffect(() => { void load(); }, [load]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const body = formObject(event.currentTarget); const payload = { ...body, start_date: body.start_date || null, release_date: body.release_date || null }; if (modal === 'new') await api(`/api/projects/${projectId}/versions`, { method: 'POST', body: JSON.stringify(payload) }); else if (modal) await api(`/api/projects/${projectId}/versions/${modal.id}`, { method: 'PATCH', body: JSON.stringify(payload) }); setModal(null); await load(); };
  const remove = async (item: Version) => { if (!confirm(`确认删除版本 ${item.name}？`)) return; await api(`/api/projects/${projectId}/versions/${item.id}`, { method: 'DELETE' }); await load(); };
  return <div className="page-stack"><PageHeader eyebrow="RELEASE MANAGEMENT" title="版本管理" description="维护版本目标、时间窗口、发布状态和发布说明。" actions={<button className="primary" onClick={() => setModal('new')}>+ 新建版本</button>}/>
    <div className="version-grid">{items.map((item) => <article className="version-card detailed" key={item.id}><div><StatusBadge value={item.status}/><button className="ghost" onClick={() => setModal(item)}>编辑</button></div><h3>{item.name}</h3><p>{item.objective || '尚未填写版本目标'}</p><dl><div><dt>开始</dt><dd>{formatDate(item.start_date)}</dd></div><div><dt>发布</dt><dd>{formatDate(item.release_date)}</dd></div></dl><footer><button className="danger-link" onClick={() => void remove(item)}>删除版本</button></footer></article>)}{!items.length && <Empty title="暂无版本" description="创建版本后可关联需求、问题和测试计划。"/>}</div>
    {modal && <Modal title={modal === 'new' ? '新建版本' : '编辑版本'} onClose={() => setModal(null)}><form className="stack" onSubmit={(event) => void save(event)}><label>版本名称<input name="name" defaultValue={modal === 'new' ? '' : modal.name} required/></label><label>版本目标<textarea name="objective" defaultValue={modal === 'new' ? '' : modal.objective} rows={3}/></label><label>状态<select name="status" defaultValue={modal === 'new' ? 'planned' : modal.status}><option value="planned">已计划</option><option value="active">进行中</option><option value="released">已发布</option><option value="archived">已归档</option></select></label><div className="two-cols"><label>开始日期<input name="start_date" type="date" defaultValue={modal === 'new' ? '' : modal.start_date?.slice(0,10) ?? ''}/></label><label>发布日期<input name="release_date" type="date" defaultValue={modal === 'new' ? '' : modal.release_date?.slice(0,10) ?? ''}/></label></div><label>发布说明<textarea name="release_notes" defaultValue={modal === 'new' ? '' : modal.release_notes} rows={4}/></label><div className="actions"><button type="button" onClick={() => setModal(null)}>取消</button><button className="primary">保存</button></div></form></Modal>}
  </div>;
}

export function Milestones({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<Milestone[]>([]); const [open, setOpen] = useState(false);
  const load = useCallback(() => api<{ items: Milestone[] }>(`/api/projects/${projectId}/milestones`).then((result) => setItems(result.items)), [projectId]);
  useEffect(() => { void load(); }, [load]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const body = formObject(event.currentTarget); await api(`/api/projects/${projectId}/milestones`, { method: 'POST', body: JSON.stringify({ ...body, due_date: body.due_date || null, progress: Number(body.progress) }) }); setOpen(false); await load(); };
  const update = async (item: Milestone, patch: object) => { await api(`/api/projects/${projectId}/milestones/${item.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); await load(); };
  const remove = async (item: Milestone) => { if (!confirm(`确认删除里程碑 ${item.title}？`)) return; await api(`/api/projects/${projectId}/milestones/${item.id}`, { method: 'DELETE' }); await load(); };
  return <div className="page-stack"><PageHeader eyebrow="DELIVERY CHECKPOINTS" title="里程碑管理" description="用关键节点、完成度和风险状态管理阶段性交付。" actions={<button className="primary" onClick={() => setOpen(true)}>+ 新建里程碑</button>}/>
    <section className="panel"><div className="milestone-board">{items.map((item) => <article key={item.id}><div className="milestone-date"><strong>{item.due_date ? new Date(`${item.due_date}T00:00:00`).getDate() : '—'}</strong><span>{item.due_date ? new Date(`${item.due_date}T00:00:00`).toLocaleDateString(undefined,{month:'short'}) : '待定'}</span></div><div className="milestone-body"><div><h3>{item.title}</h3><StatusBadge value={item.status}/></div><p>{item.description || '暂无说明'}</p><div className="row-gap"><ProgressBar value={item.progress}/><input className="progress-input" type="number" min="0" max="100" value={item.progress} onChange={(event) => void update(item, { progress: Number(event.target.value) })}/><b>%</b></div></div><button className="danger-link" onClick={() => void remove(item)}>删除</button></article>)}{!items.length && <Empty title="暂无里程碑"/>}</div></section>
    {open && <Modal title="新建里程碑" onClose={() => setOpen(false)}><form className="stack" onSubmit={(event) => void create(event)}><label>名称<input name="title" required/></label><label>说明<textarea name="description" rows={3}/></label><div className="two-cols"><label>状态<select name="status"><option value="planned">已计划</option><option value="in_progress">进行中</option><option value="at_risk">有风险</option><option value="completed">已完成</option></select></label><label>完成度<input name="progress" type="number" min="0" max="100" defaultValue="0"/></label></div><label>截止日期<input name="due_date" type="date"/></label><div className="actions"><button type="button" onClick={() => setOpen(false)}>取消</button><button className="primary">创建</button></div></form></Modal>}
  </div>;
}

export function SchedulePage({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<Schedule[]>([]); const [open, setOpen] = useState(false);
  const load = useCallback(() => api<{ items: Schedule[] }>(`/api/projects/${projectId}/schedules`).then((result) => setItems(result.items)), [projectId]);
  useEffect(() => { void load(); }, [load]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/api/projects/${projectId}/schedules`, { method: 'POST', body: JSON.stringify(formObject(event.currentTarget)) }); setOpen(false); await load(); };
  const update = async (item: Schedule, patch: object) => { await api(`/api/projects/${projectId}/schedules/${item.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); await load(); };
  const remove = async (item: Schedule) => { if (!confirm(`确认删除排期 ${item.title}？`)) return; await api(`/api/projects/${projectId}/schedules/${item.id}`, { method: 'DELETE' }); await load(); };
  const minTime = items.length ? Math.min(...items.map((item) => new Date(item.start_date).getTime())) : Date.now(); const maxTime = items.length ? Math.max(...items.map((item) => new Date(item.end_date).getTime())) : minTime + 86400000; const span = Math.max(maxTime - minTime, 86400000);
  return <div className="page-stack"><PageHeader eyebrow="DELIVERY SCHEDULE" title="进度安排" description="按时间轴查看开发、评审、测试与发布排期。" actions={<button className="primary" onClick={() => setOpen(true)}>+ 新增排期</button>}/>
    <section className="panel"><div className="timeline-head"><span>工作项</span><span>{new Date(minTime).toLocaleDateString()} — {new Date(maxTime).toLocaleDateString()}</span></div><div className="timeline">{items.map((item) => { const left = (new Date(item.start_date).getTime()-minTime)/span*100; const width = Math.max(5,(new Date(item.end_date).getTime()-new Date(item.start_date).getTime()+86400000)/span*100); return <article key={item.id}><div className="timeline-label"><strong>{item.title}</strong><span>{labels[item.schedule_type]} · {item.owner_name ?? '未分配'}</span></div><div className="timeline-track"><button style={{left:`${left}%`,width:`${Math.min(width,100-left)}%`}} className={`timeline-bar bar-${item.schedule_type}`} title={`${formatDate(item.start_date)} - ${formatDate(item.end_date)}`} onClick={() => void update(item,{status:item.status==='completed'?'in_progress':'completed'})}>{formatDate(item.start_date)} → {formatDate(item.end_date)}</button></div><StatusBadge value={item.status}/><button className="danger-link" onClick={() => void remove(item)}>删除</button></article>; })}{!items.length && <Empty title="暂无排期"/>}</div></section>
    {open && <Modal title="新增排期" onClose={() => setOpen(false)}><form className="stack" onSubmit={(event) => void create(event)}><label>事项名称<input name="title" required/></label><div className="two-cols"><label>类型<select name="schedule_type"><option value="task">任务</option><option value="review">评审</option><option value="test">测试</option><option value="release">发布</option></select></label><label>状态<select name="status"><option value="planned">已计划</option><option value="in_progress">进行中</option><option value="blocked">已阻塞</option><option value="completed">已完成</option></select></label></div><div className="two-cols"><label>开始日期<input name="start_date" type="date" required/></label><label>结束日期<input name="end_date" type="date" required/></label></div><div className="actions"><button type="button" onClick={() => setOpen(false)}>取消</button><button className="primary">创建</button></div></form></Modal>}
  </div>;
}

export function TestCases({ projectId }: { projectId: string }) {
  const [view, setView] = useState<'library'|'suites'|'coverage'>('library'); const [cases, setCases] = useState<TestCase[]>([]); const [suites, setSuites] = useState<TestSuite[]>([]); const [requirements, setRequirements] = useState<WorkItem[]>([]); const [coverage, setCoverage] = useState<CoverageItem[]>([]); const [caseOpen, setCaseOpen] = useState(false); const [suiteOpen, setSuiteOpen] = useState(false); const [query, setQuery] = useState('');
  const load = useCallback(async () => { const [caseResult,suiteResult,requirementResult,coverageResult] = await Promise.all([api<{items:TestCase[]}>(`/api/projects/${projectId}/test-cases`),api<{items:TestSuite[]}>(`/api/projects/${projectId}/test-suites`),api<{items:WorkItem[]}>(`/api/projects/${projectId}/items?kind=requirement`),api<{items:CoverageItem[]}>(`/api/projects/${projectId}/coverage`)]); setCases(caseResult.items); setSuites(suiteResult.items); setRequirements(requirementResult.items); setCoverage(coverageResult.items); }, [projectId]);
  useEffect(() => { void load(); }, [load]);
  const createCase = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const requirementIds = form.getAll('requirement_ids').map(String); const tags = String(form.get('tags') ?? '').split(',').map((value)=>value.trim()).filter(Boolean); const body = Object.fromEntries(form.entries()); delete body.requirement_ids; body.suite_id = body.suite_id || ''; const created = await api<TestCase>(`/api/projects/${projectId}/test-cases`, { method:'POST', body:JSON.stringify({...body,suite_id:body.suite_id||null,tags}) }); if(requirementIds.length) await api(`/api/projects/${projectId}/test-cases/${created.id}/requirements`,{method:'PUT',body:JSON.stringify({requirement_ids:requirementIds})}); setCaseOpen(false); await load(); };
  const createSuite = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/api/projects/${projectId}/test-suites`,{method:'POST',body:JSON.stringify(formObject(event.currentTarget))}); setSuiteOpen(false); await load(); };
  const removeCase = async (item: TestCase) => { if(!confirm(`确认删除 ${item.code}？`)) return; await api(`/api/projects/${projectId}/test-cases/${item.id}`,{method:'DELETE'}); await load(); };
  const filtered = cases.filter((item)=>!query||`${item.code} ${item.title} ${item.module}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-stack"><PageHeader eyebrow="QUALITY ASSETS" title="测试用例" description="建设可复用用例库、用例套件和需求覆盖矩阵。" actions={<><button onClick={()=>setSuiteOpen(true)}>+ 用例套件</button><button className="primary" onClick={()=>setCaseOpen(true)}>+ 新建用例</button></>}/>
    <div className="view-tabs"><button className={view==='library'?'active':''} onClick={()=>setView('library')}>用例库 <b>{cases.length}</b></button><button className={view==='suites'?'active':''} onClick={()=>setView('suites')}>用例套件 <b>{suites.length}</b></button><button className={view==='coverage'?'active':''} onClick={()=>setView('coverage')}>需求覆盖矩阵</button></div>
    {view==='library' && <section className="panel"><div className="filter-bar"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索编号、标题或模块"/><span>{filtered.length} 条用例</span></div><div className="table-wrap"><table><thead><tr><th>编号 / 标题</th><th>套件</th><th>类型</th><th>优先级</th><th>自动化</th><th>关联需求</th><th></th></tr></thead><tbody>{filtered.map((item)=><tr key={item.id}><td><span className="code">{item.code}</span><strong>{item.title}</strong><small>{item.module}</small></td><td>{item.suite_name??'未分组'}</td><td><StatusBadge value={item.case_type}/></td><td>{labels[item.priority]??item.priority}</td><td><StatusBadge value={item.automation_status}/></td><td>{item.requirement_codes?.join('、')||'未关联'}</td><td><button className="danger-link" onClick={()=>void removeCase(item)}>删除</button></td></tr>)}{!filtered.length&&<tr><td colSpan={7}><Empty title="暂无测试用例"/></td></tr>}</tbody></table></div></section>}
    {view==='suites' && <div className="suite-grid">{suites.map((suite)=><article className="suite-card" key={suite.id}><span>SUITE</span><h3>{suite.name}</h3><p>{suite.description||'暂无说明'}</p><strong>{suite.case_count} 条用例</strong></article>)}{!suites.length&&<Empty title="暂无用例套件"/>}</div>}
    {view==='coverage' && <section className="panel"><div className="table-wrap"><table><thead><tr><th>需求</th><th>状态</th><th>优先级</th><th>关联用例</th><th>通过用例</th><th>覆盖状态</th></tr></thead><tbody>{coverage.map((item)=><tr key={item.id}><td><span className="code">{item.code}</span><strong>{item.title}</strong></td><td><StatusBadge value={item.status}/></td><td>{labels[item.priority]??item.priority}</td><td>{item.case_count}</td><td>{item.passed_count}</td><td><span className={`coverage-dot ${item.case_count?'covered':'missing'}`}>{item.case_count?'已覆盖':'未覆盖'}</span></td></tr>)}{!coverage.length&&<tr><td colSpan={6}><Empty title="暂无需求"/></td></tr>}</tbody></table></div></section>}
    {caseOpen&&<Modal wide title="新建测试用例" onClose={()=>setCaseOpen(false)}><form className="stack" onSubmit={(event)=>void createCase(event)}><label>用例标题<input name="title" required/></label><div className="three-cols"><label>模块<input name="module" defaultValue="通用功能" required/></label><label>所属套件<select name="suite_id"><option value="">未分组</option>{suites.map((suite)=><option value={suite.id} key={suite.id}>{suite.name}</option>)}</select></label><label>优先级<select name="priority"><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></label></div><div className="three-cols"><label>用例类型<select name="case_type"><option value="functional">功能</option><option value="integration">集成</option><option value="regression">回归</option><option value="performance">性能</option><option value="security">安全</option><option value="usability">易用性</option></select></label><label>自动化状态<select name="automation_status"><option value="manual">手工</option><option value="candidate">可自动化</option><option value="automated">已自动化</option></select></label><label>状态<select name="status"><option value="draft">草稿</option><option value="ready">可执行</option></select></label></div><label>标签<input name="tags" placeholder="smoke, core（逗号分隔）"/></label><label>关联需求<select name="requirement_ids" multiple size={Math.min(5,Math.max(2,requirements.length))}>{requirements.map((item)=><option value={item.id} key={item.id}>{item.code} · {item.title}</option>)}</select></label><label>前置条件<textarea name="preconditions" rows={2}/></label><label>测试步骤<textarea name="steps" rows={5} required placeholder={'1. 准备测试数据\n2. 执行操作\n3. 记录结果'}/></label><label>预期结果<textarea name="expected_result" rows={3} required/></label><div className="actions"><button type="button" onClick={()=>setCaseOpen(false)}>取消</button><button className="primary">创建</button></div></form></Modal>}
    {suiteOpen&&<Modal title="新建用例套件" onClose={()=>setSuiteOpen(false)}><form className="stack" onSubmit={(event)=>void createSuite(event)}><label>套件名称<input name="name" required/></label><label>说明<textarea name="description" rows={4}/></label><div className="actions"><button type="button" onClick={()=>setSuiteOpen(false)}>取消</button><button className="primary">创建</button></div></form></Modal>}
  </div>;
}

export function TestPlans({ projectId }: { projectId: string }) {
  const [plans,setPlans]=useState<TestPlan[]>([]); const [cases,setCases]=useState<TestCase[]>([]); const [versions,setVersions]=useState<Version[]>([]); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<TestPlan|null>(null);
  const load=useCallback(async()=>{const [planResult,caseResult,versionResult]=await Promise.all([api<{items:TestPlan[]}>(`/api/projects/${projectId}/test-plans`),api<{items:TestCase[]}>(`/api/projects/${projectId}/test-cases`),api<{items:Version[]}>(`/api/projects/${projectId}/versions`)]);setPlans(planResult.items);setCases(caseResult.items);setVersions(versionResult.items);},[projectId]);
  useEffect(()=>{void load();},[load]);
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const body=formObject(event.currentTarget);await api(`/api/projects/${projectId}/test-plans`,{method:'POST',body:JSON.stringify({...body,version_id:body.version_id||null,start_date:body.start_date||null,end_date:body.end_date||null})});setOpen(false);await load();};
  const openPlan=async(plan:TestPlan)=>setSelected(await api<TestPlan>(`/api/projects/${projectId}/test-plans/${plan.id}`));
  const addAll=async()=>{if(!selected)return;const ids=cases.filter((item)=>!selected.cases?.some((current)=>current.id===item.id)).map((item)=>item.id);if(!ids.length)return;await api(`/api/projects/${projectId}/test-plans/${selected.id}/cases`,{method:'POST',body:JSON.stringify({test_case_ids:ids})});await openPlan(selected);await load();};
  const execute=async(item:TestCase,result:string)=>{if(!selected)return;await api(`/api/projects/${projectId}/test-plans/${selected.id}/cases/${item.id}`,{method:'PATCH',body:JSON.stringify({result,note:item.note??''})});await openPlan(selected);await load();};
  const remove=async(plan:TestPlan)=>{if(!confirm(`确认删除测试计划 ${plan.name}？`))return;await api(`/api/projects/${projectId}/test-plans/${plan.id}`,{method:'DELETE'});await load();};
  return <div className="page-stack"><PageHeader eyebrow="TEST EXECUTION" title="测试计划" description="组织测试范围、环境、版本与执行结果，形成可追溯记录。" actions={<button className="primary" onClick={()=>setOpen(true)}>+ 新建计划</button>}/>
    <div className="plan-grid">{plans.map((plan)=>{const executed=Number(plan.passed_count)+Number(plan.failed_count)+Number(plan.blocked_count);const rate=plan.case_count?Math.round(executed/plan.case_count*100):0;return <article className="plan-card" key={plan.id}><header><StatusBadge value={plan.status}/><button className="danger-link" onClick={()=>void remove(plan)}>删除</button></header><button className="plan-title" onClick={()=>void openPlan(plan)}>{plan.name}</button><p>{plan.description||'暂无说明'}</p><dl><div><dt>环境</dt><dd>{plan.environment}</dd></div><div><dt>版本</dt><dd>{plan.version_name??'未关联'}</dd></div><div><dt>用例</dt><dd>{plan.case_count}</dd></div><div><dt>通过</dt><dd>{plan.passed_count}</dd></div></dl><ProgressBar value={rate}/><footer>{executed}/{plan.case_count} 已执行</footer></article>})}{!plans.length&&<Empty title="暂无测试计划"/>}</div>
    {open&&<Modal title="新建测试计划" onClose={()=>setOpen(false)}><form className="stack" onSubmit={(event)=>void create(event)}><label>计划名称<input name="name" required/></label><label>计划说明<textarea name="description" rows={3}/></label><div className="two-cols"><label>执行环境<input name="environment" defaultValue="Staging" required/></label><label>关联版本<select name="version_id"><option value="">未关联</option>{versions.map((version)=><option value={version.id} key={version.id}>{version.name}</option>)}</select></label></div><label>状态<select name="status"><option value="draft">草稿</option><option value="active">执行中</option><option value="completed">已完成</option></select></label><div className="two-cols"><label>开始日期<input name="start_date" type="date"/></label><label>结束日期<input name="end_date" type="date"/></label></div><div className="actions"><button type="button" onClick={()=>setOpen(false)}>取消</button><button className="primary">创建</button></div></form></Modal>}
    {selected&&<Modal wide title={selected.name} onClose={()=>setSelected(null)}><div className="plan-detail-head"><div><StatusBadge value={selected.status}/><span>{selected.environment}</span><span>{formatDate(selected.start_date)} → {formatDate(selected.end_date)}</span></div><button onClick={()=>void addAll()}>加入全部未包含用例</button></div><div className="table-wrap"><table><thead><tr><th>用例</th><th>模块</th><th>执行结果</th><th>备注</th></tr></thead><tbody>{selected.cases?.map((item)=><tr key={item.id}><td><span className="code">{item.code}</span><strong>{item.title}</strong></td><td>{item.module}</td><td><select value={item.result??'not_run'} onChange={(event)=>void execute(item,event.target.value)}><option value="not_run">未执行</option><option value="passed">通过</option><option value="failed">失败</option><option value="blocked">阻塞</option><option value="skipped">跳过</option></select></td><td>{item.note||'—'}</td></tr>)}{!selected.cases?.length&&<tr><td colSpan={4}><Empty title="计划中暂无用例"/></td></tr>}</tbody></table></div></Modal>}
  </div>;
}

export function Reports({ projectId }: { projectId: string }) {
  const [data,setData]=useState<QualityReport|null>(null); useEffect(()=>{api<QualityReport>(`/api/projects/${projectId}/reports`).then(setData);},[projectId]); if(!data)return <div className="loading-state">正在生成质量报告…</div>;
  const executed=total(data.execution,(row)=>row.result!=='not_run'); const passed=total(data.execution,(row)=>row.result==='passed'); const passRate=executed?Math.round(passed/executed*100):0; const coverageRate=data.coverage.total?Math.round(data.coverage.covered/data.coverage.total*100):0;
  const bars=(rows:{count:number}&Record<string,unknown>)=>rows;
  return <div className="page-stack"><PageHeader eyebrow="QUALITY INSIGHTS" title="质量报告" description="统一查看范围稳定性、需求覆盖、测试执行和交付风险。" actions={<button onClick={()=>window.print()}>打印 / 导出 PDF</button>}/>
    <div className="metric-grid"><article className="metric"><span>需求覆盖率</span><strong>{coverageRate}%</strong><small>{data.coverage.covered}/{data.coverage.total} 个需求已覆盖</small></article><article className="metric"><span>测试通过率</span><strong>{passRate}%</strong><small>{passed}/{executed} 个已执行用例通过</small></article><article className="metric"><span>逾期工作项</span><strong>{data.overdue}</strong><small>未解决且超过计划日期</small></article><article className="metric"><span>风险里程碑</span><strong>{data.milestones.at_risk}</strong><small>{data.milestones.completed}/{data.milestones.total} 已完成</small></article></div>
    <div className="report-grid"><section className="panel report-panel"><h3>工作项状态</h3>{data.work_items.map((row)=>{const maximum=Math.max(...data.work_items.map((item)=>item.count),1);return <div className="report-row" key={`${row.kind}-${row.status}`}><span>{row.kind==='bug'?'问题':'需求'} · {labels[row.status]??row.status}</span><div><i style={{width:`${row.count/maximum*100}%`}}/></div><b>{row.count}</b></div>})}</section><section className="panel report-panel"><h3>测试执行结果</h3>{data.execution.map((row)=>{const maximum=Math.max(...data.execution.map((item)=>item.count),1);return <div className="report-row" key={row.result}><span>{labels[row.result]??row.result}</span><div><i className={`result-${row.result}`} style={{width:`${row.count/maximum*100}%`}}/></div><b>{row.count}</b></div>})}{!data.execution.length&&<Empty title="暂无执行数据"/>}</section></div>
  </div>;
}

export function AuditLog({ projectId }: { projectId: string }) {
  const [items,setItems]=useState<{id:number;actor_name:string;action:string;entity_type:string;payload:Record<string,unknown>;created_at:string}[]>([]); useEffect(()=>{api<{items:typeof items}>(`/api/projects/${projectId}/audit`).then((result)=>setItems(result.items));},[projectId]);
  return <div className="page-stack"><PageHeader eyebrow="TRACEABILITY" title="审计记录" description="记录关键创建、修改、执行与删除操作。"/><section className="panel"><div className="audit-list">{items.map((item)=><article key={item.id}><span className="activity-dot"/><div><strong>{item.actor_name}</strong><p>{item.action} · {item.entity_type}</p><small>{new Date(item.created_at).toLocaleString()}</small></div></article>)}{!items.length&&<Empty title="暂无审计记录"/>}</div></section></div>;
}

export function Team({ projectId, currentUser }: { projectId: string; currentUser: User }) {
  const [members,setMembers]=useState<Member[]>([]);const[directory,setDirectory]=useState<DirectoryUser[]>([]);const[showAccount,setShowAccount]=useState(false);
  const load=useCallback(async()=>{const[memberResult,directoryResult]=await Promise.all([api<{items:Member[]}>(`/api/projects/${projectId}/members`),api<{items:DirectoryUser[]}>('/api/directory')]);setMembers(memberResult.items);setDirectory(directoryResult.items);},[projectId]);useEffect(()=>{void load();},[load]);
  const available=directory.filter((person)=>!members.some((member)=>member.id===person.id));const add=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const userId=String(data.get('user_id'));if(!userId)return;await api(`/api/projects/${projectId}/members/${userId}`,{method:'PUT',body:JSON.stringify({role:data.get('role')})});await load();};
  const createAccount=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();await api('/api/users',{method:'POST',body:JSON.stringify(formObject(event.currentTarget))});setShowAccount(false);await load();};
  const remove=async(member:Member)=>{if(!confirm(`确认移除 ${member.display_name}？`))return;await api(`/api/projects/${projectId}/members/${member.id}`,{method:'DELETE'});await load();};
  return <div className="page-stack"><PageHeader eyebrow="COLLABORATION" title="项目团队" description="管理项目成员、角色与访问范围。" actions={currentUser.role==='admin'?<button onClick={()=>setShowAccount(true)}>+ 创建账号</button>:undefined}/><section className="panel"><form className="inline-form" onSubmit={(event)=>void add(event)}><select name="user_id" required defaultValue=""><option value="" disabled>选择已有账号</option>{available.map((person)=><option key={person.id} value={person.id}>{person.display_name} · {person.email}</option>)}</select><select name="role" defaultValue="member"><option value="owner">负责人</option><option value="member">成员</option><option value="viewer">只读</option></select><button className="primary">添加成员</button></form><div className="member-grid">{members.map((member)=><article key={member.id}><span className="avatar large">{member.display_name.slice(0,1).toUpperCase()}</span><div><strong>{member.display_name}</strong><small>{member.email}</small><StatusBadge value={member.role}/></div><button className="danger-link" onClick={()=>void remove(member)}>移除</button></article>)}</div></section>{showAccount&&<Modal title="创建账号" onClose={()=>setShowAccount(false)}><form className="stack" onSubmit={(event)=>void createAccount(event)}><label>姓名<input name="display_name" required/></label><label>邮箱<input name="email" type="email" required/></label><label>初始密码<input name="password" type="password" minLength={12} required/></label><label>系统角色<select name="role"><option value="user">普通用户</option><option value="admin">管理员</option></select></label><div className="actions"><button type="button" onClick={()=>setShowAccount(false)}>取消</button><button className="primary">创建账号</button></div></form></Modal>}</div>;
}
